# Generated by Django 3.2 on 2021-05-04 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_testtable'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestTable',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
