# Generated by Django 3.2 on 2021-05-13 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_testtable'),
        ('users', '0004_profileversiontwo'),
    ]

    operations = [
    ]
