# Generated by Django 3.2 on 2021-05-13 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_merge_0002_testtable_0004_profileversiontwo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestTable',
        ),
    ]
