# Generated by Django 3.2 on 2021-05-11 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_search'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
