# Generated by Django 3.2 on 2021-05-11 15:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_profile', '0004_alter_search_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterUniqueTogether(
            name='search',
            unique_together={('user', 'keyword')},
        ),
    ]
