# Generated by Django 3.2 on 2021-05-13 13:56

from django.conf import settings
from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0004_auto_20210505_0920'),
        ('order', '0003_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paymentinfo',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
        migrations.AlterUniqueTogether(
            name='cart',
            unique_together={('user', 'product')},
        ),
    ]
